# Generated by Django 2.2.1 on 2019-05-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_order',
            field=models.IntegerField(default=20),
        ),
    ]
