# Generated by Django 2.2.1 on 2019-05-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190512_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='intro_text',
            new_name='about',
        ),
    ]
