# Generated by Django 2.2.1 on 2019-05-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20190517_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
